import Rating from "@/components/rating";
import {ClipboardEdit, Home, ShoppingCart, Ticket, User2} from "lucide-react";

export const navLinks = [
  {
    link: "/",
    title: "link",
  },
];

export const FAQs = [
  {title: "FAQ 1", description: "FAQ 1 description"},
  {title: "FAQ 2", description: "FAQ 2 description"},
  {title: "FAQ 3", description: "FAQ 3 description"},
  {title: "FAQ 4", description: "FAQ 4 description"},
  {title: "FAQ 5", description: "FAQ 5 description"},
];

export const sideBar = [
  {
    img: "",
    href: "/dashboard",
    link: "Dashboard",
    Icon: Home,
  },
  {
    img: "",
    href: "/dashboard/products",
    link: "Products",
    Icon: ShoppingCart,
  },
  {
    img: "",
    href: "/dashboard/orders",
    link: "Orders",
    Icon: ClipboardEdit,
  },
  {
    img: "",
    href: "/dashboard/users",
    link: "Users",
    Icon: User2,
  },
  {
    img: "",
    href: "/dashboard/tickets",
    link: "Tickets",
    Icon: Ticket,
  },
];

export const userRoles = [
  {role: "Super Admin", label: "Super Admin"},
  {role: "Admin", label: "Admin"},
  {role: "user", label: "User"},
];

export const userStatus = [
  {status: "active", color: "#2fd91c"},
  {status: "suspended", color: "#d9534f"},
  {status: "banned", color: "#ff0000"},
];

export const orderStatus = [
  {
    status: "pending",
    color: "#FFA500",
  },
  {
    status: "paid",
    color: "#16a61f",
  },
  {
    status: "confirmed",
    color: "#32CD32",
  },
  {
    status: "processing",
    color: "#FFD700",
  },
  {
    status: "shipped",
    color: "#1E90FF",
  },
  {
    status: "delivered",
    color: "#228B22",
  },
  {
    status: "cancelled",
    color: "#FF4500",
  },
  {
    status: "returned",
    color: "#FF6347",
  },
  {
    status: "refunded",
    color: "#8A2BE2",
  },
  {
    status: "failed",
    color: "#B22222",
  },
];

export const orders = [
  {
    id: "order1",
    email: "email1@email.com",
    status: "pending",
    quantity: 5,
    method: "pay on delivary",
    total: 100,
    products: [
      {
        id: "p1",
        img: "/laptop1.jpg",
        title: "product title fklaj lfdkjs alakdfj lakdfj lakdfj alkdfj lksjf laksdfj",
        quantity: 3,
        price: 120,
      },
      {id: "p2", img: "/desktop2.jpg", title: "product title", quantity: 1, price: 120},
      {id: "p3", img: "/phone3.jpg", title: "product title", quantity: 1, price: 120},
    ],
    address: {
      id: "id1",
      name: "first last",
      address: "address 1",
      postal: "1000",
      city: "city",
      state: "state",
      streetNumber: "street number",
      phone: "23093203",
    },
  },
  {
    id: "order2",
    email: "email1@email.com",
    status: "pending",
    quantity: 5,
    method: "pay on delivary",
    total: 100,
    products: [
      {id: "p1", img: "/laptop1.jpg", title: "product title", quantity: 3, price: 120},
      {id: "p2", img: "/desktop2.jpg", title: "product title", quantity: 1, price: 120},
      {id: "p3", img: "/phone3.jpg", title: "product title", quantity: 1, price: 120},
    ],
    address: {
      id: "id1",
      name: "first last",
      address: "address 1",
      postal: "1000",
      city: "city",
      state: "state",
      streetNumber: "street number",
      phone: "23093203",
    },
  },
  {
    id: "order3",
    email: "email1@email.com",
    status: "pending",
    quantity: 5,
    method: "pay on delivary",
    total: 100,
    products: [
      {id: "p1", img: "/laptop1.jpg", title: "product title", quantity: 3, price: 120},
      {id: "p2", img: "/desktop2.jpg", title: "product title", quantity: 1, price: 120},
      {id: "p3", img: "/phone3.jpg", title: "product title", quantity: 1, price: 120},
    ],
    address: {
      id: "id1",
      name: "first last",
      address: "address 1",
      postal: "1000",
      city: "city",
      state: "state",
      streetNumber: "street number",
      phone: "23093203",
    },
  },
  {
    id: "order4",
    email: "email1@email.com",
    status: "pending",
    quantity: 5,
    method: "pay on delivary",
    total: 100,
    products: [
      {id: "p1", img: "/laptop1.jpg", title: "product title", quantity: 3, price: 120},
      {id: "p2", img: "/desktop2.jpg", title: "product title", quantity: 1, price: 100},
      {id: "p3", img: "/phone3.jpg", title: "product title", quantity: 1, price: 320},
    ],
    address: {
      id: "id1",
      name: "first last",
      address: "address 1",
      postal: "1000",
      city: "city",
      state: "state",
      streetNumber: "street number",
      phone: "23093203",
    },
  },
];

export const products = [
  {
    id: "1",
    name: "product1",
    description: "description1",
    specs: "<h1>specs</h1>",
    original_price: 10,
    discount: 20,
    price: 8,
    max_quantity: 10,
    category: "electronics",
    sub_category: "laptops",
    tags: [
      {tag_name: "cpu", value: "i5"},
      {tag_name: "graphics-card", value: "rtx-4080"},
      {tag_name: "ram", value: "16gb"},
      {tag_name: "reresh-rate", value: "60hz"},
    ],
    reviews: 3,
    rating: 3,
    main_img: "/desktop2.jpg",
    media: ["/laptop1.jpg", "/laptop2.jpg", "/laptop3.jpg"],
    created_at: "date",
  },
  {
    id: "2",
    name: "product1",
    description: "description1",
    specs: "<h1>specs</h1>",
    original_price: 10,
    discount: 20,
    price: 8,
    max_quantity: 10,
    category: "electronics",
    sub_category: "laptops",
    tags: [
      {tag_name: "cpu", value: "i7"},
      {tag_name: "graphics-card", value: "rtx-3070"},
      {tag_name: "ram", value: "32gb"},
      {tag_name: "refresh-rate", value: "144hz"},
    ],
    reviews: 3,
    rating: 3,
    main_img: "/laptop1.jpg",
    media: ["/laptop1.jpg", "/laptop2.jpg", "/laptop3.jpg"],
    created_at: "date",
  },
  {
    id: "3",
    name: "product1",
    description: "description1",
    specs: "<h1>specs</h1>",
    original_price: 10,
    discount: 20,
    price: 8,
    max_quantity: 10,
    category: "electronics",
    sub_category: "laptops",
    tags: [
      {tag_name: "cpu", value: "i9"},
      {tag_name: "graphics-card", value: "gtx-1660"},
      {tag_name: "ram", value: "8gb"},
      {tag_name: "refresh-rate", value: "120hz"},
    ],
    reviews: 3,
    rating: 3,
    main_img: "/laptop2.jpg",
    media: ["/laptop1.jpg", "/laptop2.jpg", "/laptop3.jpg"],
    created_at: "date",
  },
  {
    id: "4",
    name: "product1",
    description: "description1",
    specs: "<h1>specs</h1>",
    original_price: 10,
    discount: 20,
    price: 8,
    max_quantity: 10,
    category: "electronics",
    sub_category: "laptops",
    tags: [
      {tag_name: "cpu", value: "ryzen-5"},
      {tag_name: "graphics-card", value: "rx-5700"},
      {tag_name: "ram", value: "16gb"},
      {tag_name: "refresh-rate", value: "75hz"},
    ],
    reviews: 3,
    rating: 3,
    main_img: "/desktop1.jpg",
    media: ["/laptop1.jpg", "/laptop2.jpg", "/laptop3.jpg"],
    created_at: "date",
  },
  {
    id: "5",
    name: "product1",
    description: "description1",
    specs: "<h1>specs</h1>",
    original_price: 10,
    discount: 20,
    price: 8,
    max_quantity: 10,
    category: "electronics",
    sub_category: "laptops",
    tags: [
      {tag_name: "cpu", value: "ryzen-7"},
      {tag_name: "graphics-card", value: "rtx-2060"},
      {tag_name: "ram", value: "64gb"},
      {tag_name: "refresh-rate", value: "240hz"},
    ],
    reviews: 3,
    rating: 3,
    main_img: "/phone1.jpg",
    media: ["/laptop1.jpg", "/laptop2.jpg", "/laptop3.jpg"],
    created_at: "date",
  },
];

export const categories = [
  {
    title: "Electronics",
    label: "electronics",
    link: "/products/electronics",
    sub: [
      {title: "Laptops", label: "laptops", link: "/products/laptops"},
      {title: "Smartphones", label: "smartphones", link: "/products/smartphones"},
      {title: "Tablets", label: "tablets", link: "/products/tablets"},
      {title: "Televisions", label: "televisions", link: "/products/televisions"},
      {title: "Headphones", label: "headphones", link: "/products/headphones"},
      {title: "Cameras", label: "cameras", link: "/products/cameras"},
      {
        title: "Gaming Consoles",
        label: "gaming-consoles",
        link: "/products/gaming-consoles",
      },
      {title: "Audio Systems", label: "audio-systems", link: "/products/audio-systems"},
      {title: "Smartwatches", label: "smartwatches", link: "/products/smartwatches"},
      {
        title: "Computer Accessories",
        label: "computer-accessories",
        link: "/products/computer-accessories",
      },
    ],
  },
  {
    title: "Clothing & Accessories",
    label: "clothing-accessories",
    link: "/products/clothing-accessories",
    sub: [
      {title: "Men's Clothing", label: "mens-clothing", link: "/products/mens-clothing"},
      {
        title: "Women's Clothing",
        label: "womens-clothing",
        link: "/products/womens-clothing",
      },
      {title: "Kids' Clothing", label: "kids-clothing", link: "/products/kids-clothing"},
      {title: "Shoes", label: "shoes", link: "/products/shoes"},
      {title: "Bags & Wallets", label: "bags-wallets", link: "/products/bags-wallets"},
      {title: "Jewelry", label: "jewelry", link: "/products/jewelry"},
      {title: "Watches", label: "watches", link: "/products/watches"},
      {title: "Accessories", label: "accessories", link: "/products/accessories"},
      {title: "Sportswear", label: "sportswear", link: "/products/sportswear"},
      {
        title: "Underwear & Sleepwear",
        label: "underwear-sleepwear",
        link: "/products/underwear-sleepwear",
      },
    ],
  },
  {
    title: "Home & Garden",
    label: "home-garden",
    link: "/products/home-garden",
    sub: [
      {title: "Furniture", label: "furniture", link: "/products/furniture"},
      {title: "Home Decor", label: "home-decor", link: "/products/home-decor"},
      {title: "Bedding & Bath", label: "bedding-bath", link: "/products/bedding-bath"},
      {
        title: "Kitchen & Dining",
        label: "kitchen-dining",
        link: "/products/kitchen-dining",
      },
      {title: "Appliances", label: "appliances", link: "/products/appliances"},
      {title: "Gardening", label: "gardening", link: "/products/gardening"},
      {title: "Lighting", label: "lighting", link: "/products/lighting"},
      {
        title: "Storage & Organization",
        label: "storage-organization",
        link: "/products/storage-organization",
      },
      {
        title: "Cleaning Supplies",
        label: "cleaning-supplies",
        link: "/products/cleaning-supplies",
      },
      {
        title: "Home Improvement",
        label: "home-improvement",
        link: "/products/home-improvement",
      },
    ],
  },
  {
    title: "Beauty & Personal Care",
    label: "beauty-personal-care",
    link: "/products/beauty-personal-care",
    sub: [
      {title: "Skincare", label: "skincare", link: "/products/skincare"},
      {title: "Makeup", label: "makeup", link: "/products/makeup"},
      {title: "Hair Care", label: "hair-care", link: "/products/hair-care"},
      {title: "Fragrances", label: "fragrances", link: "/products/fragrances"},
      {title: "Bath & Body", label: "bath-body", link: "/products/bath-body"},
      {title: "Oral Care", label: "oral-care", link: "/products/oral-care"},
      {title: "Men's Grooming", label: "mens-grooming", link: "/products/mens-grooming"},
      {
        title: "Tools & Accessories",
        label: "beauty-tools",
        link: "/products/beauty-tools",
      },
      {title: "Nail Care", label: "nail-care", link: "/products/nail-care"},
      {title: "Sun Care", label: "sun-care", link: "/products/sun-care"},
    ],
  },
  {
    title: "Books & Media",
    label: "books-media",
    link: "/products/books-media",
    sub: [
      {title: "Fiction Books", label: "fiction-books", link: "/products/fiction-books"},
      {
        title: "Non-Fiction Books",
        label: "non-fiction-books",
        link: "/products/non-fiction-books",
      },
      {title: "E-books", label: "e-books", link: "/products/e-books"},
      {title: "Audiobooks", label: "audiobooks", link: "/products/audiobooks"},
      {title: "Movies & TV Shows", label: "movies-tv", link: "/products/movies-tv"},
      {title: "Music", label: "music", link: "/products/music"},
      {title: "Video Games", label: "video-games", link: "/products/video-games"},
      {title: "Magazines", label: "magazines", link: "/products/magazines"},
      {
        title: "Comics & Graphic Novels",
        label: "comics-graphic-novels",
        link: "/products/comics-graphic-novels",
      },
      {
        title: "Educational Materials",
        label: "educational-materials",
        link: "/products/educational-materials",
      },
    ],
  },
  {
    title: "Sports & Outdoors",
    label: "sports-outdoors",
    link: "/products/sports-outdoors",
    sub: [
      {
        title: "Exercise & Fitness",
        label: "exercise-fitness",
        link: "/products/exercise-fitness",
      },
      {
        title: "Outdoor Recreation",
        label: "outdoor-recreation",
        link: "/products/outdoor-recreation",
      },
      {title: "Team Sports", label: "team-sports", link: "/products/team-sports"},
      {
        title: "Camping & Hiking",
        label: "camping-hiking",
        link: "/products/camping-hiking",
      },
      {title: "Cycling", label: "cycling", link: "/products/cycling"},
      {title: "Water Sports", label: "water-sports", link: "/products/water-sports"},
      {title: "Winter Sports", label: "winter-sports", link: "/products/winter-sports"},
      {
        title: "Hunting & Fishing",
        label: "hunting-fishing",
        link: "/products/hunting-fishing",
      },
      {
        title: "Sports Apparel",
        label: "sports-apparel",
        link: "/products/sports-apparel",
      },
      {
        title: "Sports Accessories",
        label: "sports-accessories",
        link: "/products/sports-accessories",
      },
    ],
  },
  {
    title: "Toys & Games",
    label: "toys-games",
    link: "/products/toys-games",
    sub: [
      {
        title: "Action Figures",
        label: "action-figures",
        link: "/products/action-figures",
      },
      {title: "Board Games", label: "board-games", link: "/products/board-games"},
      {title: "Building Toys", label: "building-toys", link: "/products/building-toys"},
      {
        title: "Dolls & Accessories",
        label: "dolls-accessories",
        link: "/products/dolls-accessories",
      },
      {
        title: "Educational Toys",
        label: "educational-toys",
        link: "/products/educational-toys",
      },
      {title: "Outdoor Play", label: "outdoor-play", link: "/products/outdoor-play"},
      {title: "Puzzles", label: "puzzles", link: "/products/puzzles"},
      {
        title: "Remote Control Toys",
        label: "remote-control-toys",
        link: "/products/remote-control-toys",
      },
      {
        title: "Stuffed Animals",
        label: "stuffed-animals",
        link: "/products/stuffed-animals",
      },
      {title: "Video Games", label: "video-games", link: "/products/video-games"},
    ],
  },
  {
    title: "Health & Wellness",
    label: "health-wellness",
    link: "/products/health-wellness",
    sub: [
      {
        title: "Vitamins & Supplements",
        label: "vitamins-supplements",
        link: "/products/vitamins-supplements",
      },
      {
        title: "Fitness Equipment",
        label: "fitness-equipment",
        link: "/products/fitness-equipment",
      },
      {title: "Personal Care", label: "personal-care", link: "/products/personal-care"},
      {
        title: "Nutrition & Diet",
        label: "nutrition-diet",
        link: "/products/nutrition-diet",
      },
      {
        title: "Medical Supplies",
        label: "medical-supplies",
        link: "/products/medical-supplies",
      },
      {
        title: "Mental Wellness",
        label: "mental-wellness",
        link: "/products/mental-wellness",
      },
      {
        title: "Sleep & Relaxation",
        label: "sleep-relaxation",
        link: "/products/sleep-relaxation",
      },
      {
        title: "Alternative Medicine",
        label: "alternative-medicine",
        link: "/products/alternative-medicine",
      },
      {
        title: "Health Monitors",
        label: "health-monitors",
        link: "/products/health-monitors",
      },
      {title: "First Aid", label: "first-aid", link: "/products/first-aid"},
    ],
  },
  {
    title: "Automotive",
    label: "automotive",
    link: "/products/automotive",
    sub: [
      {
        title: "Car Parts & Accessories",
        label: "car-parts-accessories",
        link: "/products/car-parts-accessories",
      },
      {
        title: "Tools & Equipment",
        label: "automotive-tools",
        link: "/products/automotive-tools",
      },
      {title: "Car Care", label: "car-care", link: "/products/car-care"},
      {
        title: "Electronics & Navigation",
        label: "auto-electronics",
        link: "/products/auto-electronics",
      },
      {title: "Tires & Wheels", label: "tires-wheels", link: "/products/tires-wheels"},
      {
        title: "Motorcycle Parts",
        label: "motorcycle-parts",
        link: "/products/motorcycle-parts",
      },
      {title: "Oils & Fluids", label: "oils-fluids", link: "/products/oils-fluids"},
      {
        title: "Paint & Body Repair",
        label: "paint-body-repair",
        link: "/products/paint-body-repair",
      },
      {
        title: "Interior Accessories",
        label: "interior-accessories",
        link: "/products/interior-accessories",
      },
      {
        title: "Performance Parts",
        label: "performance-parts",
        link: "/products/performance-parts",
      },
    ],
  },
  {
    title: "Groceries & Food",
    label: "groceries-food",
    link: "/products/groceries-food",
    sub: [
      {title: "Fresh Produce", label: "fresh-produce", link: "/products/fresh-produce"},
      {title: "Dairy & Eggs", label: "dairy-eggs", link: "/products/dairy-eggs"},
      {title: "Meat & Seafood", label: "meat-seafood", link: "/products/meat-seafood"},
      {title: "Bakery", label: "bakery", link: "/products/bakery"},
      {
        title: "Pantry Staples",
        label: "pantry-staples",
        link: "/products/pantry-staples",
      },
      {title: "Snacks", label: "snacks", link: "/products/snacks"},
      {title: "Beverages", label: "beverages", link: "/products/beverages"},
      {title: "Frozen Foods", label: "frozen-foods", link: "/products/frozen-foods"},
      {
        title: "Organic & Natural",
        label: "organic-natural",
        link: "/products/organic-natural",
      },
      {
        title: "International Foods",
        label: "international-foods",
        link: "/products/international-foods",
      },
    ],
  },
];

export const filters = [
  {
    title: "Reviews",
    label: "reviews",
    category: ["all"],
    type: "reviews",
    filters: [
      {name: "1", slug: "1"},
      {name: "2", slug: "2"},
      {name: "3", slug: "3"},
      {name: "4", slug: "4"},
      {name: "5", slug: "5"},
    ],
  },
  {
    title: "Color",
    label: "color",
    category: ["all"],
    type: "checkbox",
    filters: [
      {name: "Black", slug: "color-black"},
      {name: "White", slug: "color-white"},
      {name: "Red", slug: "color-red"},
      {name: "Blue", slug: "color-blue"},
      {name: "Green", slug: "color-green"},
    ],
  },
  {
    title: "graphics card",
    label: "graphics-card",
    category: ["laptops", "gaming-pc", "gaming-laptop"],
    type: "radio",
    filters: [
      {name: "RTX 4060", slug: "rtx-4060"},
      {name: "RTX 4070", slug: "rtx-4070"},
      {name: "RTX 4080", slug: "rtx-4080"},
      {name: "RTX 4090", slug: "rtx-4090"},
    ],
  },
  {
    title: "CPU",
    label: "cpu",
    category: ["laptops", "gaming-pc", "gaming-laptop"],
    type: "checkbox",
    filters: [
      {name: "intel i5-5500", slug: "i5-5500"},
      {name: "intel i5-5600", slug: "i5-5600"},
      {name: "intel i5-5700", slug: "i5-5700"},
      {name: "intel i5-5800", slug: "i5-5800"},
    ],
  },
  {
    title: "RAM",
    label: "ram",
    category: ["laptops", "gaming-pc", "gaming-laptop"],
    type: "checkbox",
    filters: [
      {name: "4 GB", slug: "ram-4-gb"},
      {name: "8 GB", slug: "ram-8-gb"},
      {name: "16 GB", slug: "ram-16-gb"},
      {name: "32 GB", slug: "ram-32-gb"},
    ],
  },
  {
    title: "Screen Size",
    label: "screen-size",
    category: ["monitor", "tv", "laptops"],
    type: "checkbox",
    filters: [
      {name: "13-14 inch", slug: "screen-size-13-14-inch"},
      {name: "15-16 inch", slug: "screen-size-15-16-inch"},
      {name: "17-18 inch", slug: "screen-size-17-18-inch"},
      {name: "21-24 inch", slug: "screen-size-21-24-inch"},
      {name: "27-32 inch", slug: "screen-size-27-32-inch"},
      {name: "34 inch and above", slug: "screen-size-34-inch-and-above"},
    ],
  },
  {
    title: "CPU",
    label: "phone-cpu",
    category: ["phone", "smartphones"],
    type: "checkbox",
    filters: [
      {name: "Snapdragon 8 Gen 2", slug: "cpu-snapdragon-8-gen-2"},
      {name: "A16 Bionic", slug: "cpu-a16-bionic"},
      {name: "Exynos 2200", slug: "cpu-exynos-2200"},
      {name: "MediaTek Dimensity 9000", slug: "cpu-mediatek-dimensity-9000"},
      {name: "Google Tensor G2", slug: "cpu-google-tensor-g2"},
    ],
  },
  {
    title: "RAM",
    label: "phone-ram",
    category: ["phone", "smartphones"],
    type: "checkbox",
    filters: [
      {name: "4 GB", slug: "phone-ram-4-gb"},
      {name: "6 GB", slug: "phone-ram-6-gb"},
      {name: "8 GB", slug: "phone-ram-8-gb"},
      {name: "12 GB", slug: "phone-ram-12-gb"},
      {name: "16 GB", slug: "phone-ram-16-gb"},
    ],
  },
  {
    title: "Storage",
    label: "phone-storage",
    category: ["phone", "smartphones"],
    type: "checkbox",
    filters: [
      {name: "64 GB", slug: "phone-storage-64-gb"},
      {name: "128 GB", slug: "phone-storage-128-gb"},
      {name: "256 GB", slug: "phone-storage-256-gb"},
      {name: "512 GB", slug: "phone-storage-512-gb"},
      {name: "1 TB", slug: "phone-storage-1-tb"},
    ],
  },
  {
    title: "Screen Resolution",
    label: "phone-resolution",
    category: ["phone", "smartphones"],
    type: "checkbox",
    filters: [
      {name: "HD (720p)", slug: "phone-resolution-hd"},
      {name: "Full HD (1080p)", slug: "phone-resolution-full-hd"},
      {name: "QHD (1440p)", slug: "phone-resolution-qhd"},
      {name: "4K (2160p)", slug: "phone-resolution-4k"},
    ],
  },
  {
    title: "Camera Resolution",
    label: "camera-resolution",
    category: ["phone", "tablet", "camera"],
    type: "checkbox",
    filters: [
      {name: "12 MP", slug: "camera-resolution-12-mp"},
      {name: "16 MP", slug: "camera-resolution-16-mp"},
      {name: "24 MP", slug: "camera-resolution-24-mp"},
      {name: "48 MP", slug: "camera-resolution-48-mp"},
      {name: "64 MP and above", slug: "camera-resolution-64-mp-and-above"},
    ],
  },
  {
    title: "Size",
    label: "size",
    category: ["cloths"],
    type: "checkbox",
    filters: [
      {name: "S", slug: "size-s"},
      {name: "M", slug: "size-m"},
      {name: "L", slug: "size-l"},
      {name: "XL", slug: "size-xl"},
    ],
  },
  {
    title: "Book Genre",
    label: "book-genre",
    category: ["books"],
    type: "checkbox",
    filters: [
      {name: "Fiction", slug: "genre-fiction"},
      {name: "Non-fiction", slug: "genre-non-fiction"},
      {name: "Mystery", slug: "genre-mystery"},
      {name: "Science Fiction", slug: "genre-sci-fi"},
      {name: "Biography", slug: "genre-biography"},
    ],
  },
  {
    title: "Shoe Size",
    label: "shoe-size",
    category: ["shoes"],
    type: "checkbox",
    filters: [
      {name: "6", slug: "shoe-size-6"},
      {name: "7", slug: "shoe-size-7"},
      {name: "8", slug: "shoe-size-8"},
      {name: "9", slug: "shoe-size-9"},
      {name: "10", slug: "shoe-size-10"},
    ],
  },
  {
    title: "Energy Efficiency",
    label: "energy-efficiency",
    category: ["appliances", "electronics"],
    type: "checkbox",
    filters: [
      {name: "A+++", slug: "energy-a-plus-plus-plus"},
      {name: "A++", slug: "energy-a-plus-plus"},
      {name: "A+", slug: "energy-a-plus"},
      {name: "A", slug: "energy-a"},
      {name: "B", slug: "energy-b"},
    ],
  },
  {
    title: "Material",
    label: "material",
    category: ["furniture", "clothing", "accessories"],
    type: "checkbox",
    filters: [
      {name: "Cotton", slug: "material-cotton"},
      {name: "Leather", slug: "material-leather"},
      {name: "Wood", slug: "material-wood"},
      {name: "Metal", slug: "material-metal"},
      {name: "Plastic", slug: "material-plastic"},
    ],
  },
];

export const availableTags = {
  names: [
    {name: "CPU", label: "cpu"},
    {name: "Graphics Card", label: "graphics"},
  ],
  values: {
    cpu: [
      {name: "i5", label: "i5"},
      {name: "i3", label: "i3"},
      {name: "i7", label: "i7"},
      {name: "i9", label: "i9"},
    ],
    graphics: [
      {name: "RTX 4090", label: "rtx-4090"},
      {name: "RTX 4080", label: "rtx-4080"},
      {name: "RTX 4060", label: "rtx-4060"},
    ],
  },
};
