import {getUser} from "@/actions/users";
import {ThemeProvider} from "@/components/theme-provider";
import {Toaster} from "@/components/ui/toaster";
import {UserProvider} from "@/context/userContext";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../globals.css";
import SideBar from "./_components/SideBar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userData = await getUser();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} id="dashboard-page">
        <UserProvider initialUser={userData}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <SideBar userData={userData} />
            {children}
            <Toaster />
          </ThemeProvider>
        </UserProvider>
      </body>
    </html>
  );
}
